# Generated by Django 4.2.2 on 2023-06-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('surname', models.CharField(max_length=150)),
                ('age', models.DateTimeField(auto_now=True)),
                ('address', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='media/%Y/%m/%d')),
            ],
        ),
    ]
