# Generated by Django 4.2.2 on 2023-06-29 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Human', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='human',
            options={'ordering': ['age'], 'verbose_name': 'человек', 'verbose_name_plural': 'люди'},
        ),
        migrations.AddField(
            model_name='human',
            name='content',
            field=models.TextField(blank=True, verbose_name='Резюме'),
        ),
        migrations.AlterField(
            model_name='human',
            name='address',
            field=models.TextField(blank=True, verbose_name='АДРЕС ПРОЖИВАНИЯ'),
        ),
        migrations.AlterField(
            model_name='human',
            name='age',
            field=models.DateTimeField(auto_now=True, verbose_name='ВОЗРАСТ'),
        ),
        migrations.AlterField(
            model_name='human',
            name='name',
            field=models.CharField(max_length=150, verbose_name='ИМЯ'),
        ),
        migrations.AlterField(
            model_name='human',
            name='photo',
            field=models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='ФОТО'),
        ),
        migrations.AlterField(
            model_name='human',
            name='surname',
            field=models.CharField(max_length=150, verbose_name='ФАМИЛИЯ'),
        ),
        migrations.AddField(
            model_name='human',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Human.profession', verbose_name='Профессия'),
        ),
    ]
